questions = [
    "Little interest or pleasure in doing things?",
    "Feeling down, depressed, or hopeless?",
    "Trouble falling or staying asleep, or sleeping too much?",
    "Feeling tired or having little energy?",
    "Poor appetite or overeating?",
    "Feeling bad about yourself - or that you're a failure or have let yourself or your family down?",
    "Trouble concentrating on things, such as reading the newspaper or watching television?",
    "Moving or speaking so slowly that other people could have noticed? Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual?",
    "Thoughts that you would be better off dead, or of hurting yourself in some way?",
    "Do you often feel anxious or worried?",
]

subjective_question = [
    "What brings you in today?",
    "Can you describe your current symptoms?",
    "When did your symptoms first begin?",
    "Have you experienced these symptoms before?",
    "Do you have a history of mental health problems or psychiatric treatment?",
    "Do you have any medical conditions or take any medications?",
    "Have you experienced any traumatic events or stressful situations recently?",
    "How has your mood been lately?",
    "Have you experienced any changes in appetite or sleep patterns?",
    "Do you have any thoughts of hurting yourself or others?",
    "Over the past two weeks, how often have you been bothered by feeling down, depressed, or hopeless?",
    "Over the past two weeks, how often have you been bothered by little interest or pleasure in doing things?",
    "Have you had any changes in appetite or weight recently?",
    "Have you had any changes in sleep patterns recently?",
    "Have you experienced any feelings of worthlessness or guilt?",
    "Have you experienced any thoughts of death or suicide?",
]
